VERSION="1.0.0"

ACCOUNTS=[
    "GDHGMBQG2KXGZNMG3YIH2CRBUVA6C6ZE5LGPAGN4V74UADQCGBZ2BKU2",
]

[DOCUMENTATION]
ORG_NAME="Luis"
ORG_URL="https://www.luishauenstein.com"
ORG_LOGO="https://i.ibb.co/K7tR0R5/logo.png"
ORG_DESCRIPTION="BEST-themed snake game. Not affiliated with Bitpanda."

[[PRINCIPALS]]
github="luishauenstein"